"""
Database service for executing SQL queries generated by LLM
"""

import json
from typing import List, Dict, Any, Optional
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker
from ..config import config
import logging
import os

logger = logging.getLogger(__name__)


class DatabaseService:
    """Service for executing SQL queries generated by LLM"""
    
    def __init__(self):
        """Initialize database connection"""
        self.database_url = config.database_url
        # Ensure the database file path is absolute for SQLite
        if self.database_url.startswith("sqlite:///"):
            db_path = self.database_url.replace("sqlite:///", "")
            if not os.path.isabs(db_path):
                db_path = os.path.abspath(db_path)
            self.database_url = f"sqlite:///{db_path}"
        
        self.engine = create_engine(
            self.database_url, 
            echo=False,
            connect_args={"check_same_thread": False}  # SQLite specific
        )
        self.SessionLocal = sessionmaker(
            bind=self.engine,
            expire_on_commit=False
        )
        
        # Database schema information for LLM context
        self.schema_info = self._get_schema_info()
    
    def _get_schema_info(self) -> str:
        """Get database schema information for LLM context"""
        return """
        Database Schema for Hubble System:
        
        Tables and their key columns:
        
        1. users - Employee information
           - id, employee_id, email, name, username, status - ENUM(intern, probationer, working, in-notice-period, relieved, project_intern), team_id, branch_id, designation_id
           - first_name, last_name, is_employed, active_status, personal_email
           - created_at, updated_at, deleted_at
        
        2. branches - Office locations
           - id, name, street, city, state, country, pincode, latitude, longitude
           - type, percentage, check_in_time, professional_tax
        
        3. teams - Team information
           - id, name, type, started_at, owner_id
        
        4. designations - Job positions
           - id, name, type, required_reporting_person, referral_bonus
        
        5. projects - Project information
           - id, project_id, name, status, version, billing_frequency
           - client_id, currency_id, project_owner_id, project_manager_id
           - parent_project_id, project_end_date
        
        6. parent_projects - Parent project information
           - id, parent_project_id, name, status, billing_frequency
           - client_id, currency_id, project_owner_id, parent_project_end_date
        
        7. leaves - Leave records
           - id, user_id, date, reason, category, status, type
           - applied_by, approved_by, sl_approved_by, reject_reason
           - created_at, updated_at, deleted_at
        
        8. leave_balances - Leave balance tracking
           - id, user_id, lop, action, earned_leaves, casual_leaves, sick_leaves
           - updated_by, leave_id, lop_categories
        
        9. casual_leaves - Casual leave configuration
           - id, days, year, updated_by, type
        
        10. holidays - Company holidays
            - id, date_of_holiday, month_year, reason, allow_check_in, national_holiday
            - updated_by, created_at, updated_at, deleted_at
        
        11. timeoffs - Time off requests
            - id, user_id, date, start_time, end_time, reason, status
            - applied_by, approved_by, reject_reason, time_changes
        
        12. timesheet_entries - Work time tracking
            - id, user_id, project_id, module_id, task_id, description
            - entry_date, working_hours, approved_hours, authorized_hours, billed_hours
            - team_id, admin_comments
        
        13. cards - Task/assignment cards
            - id, project_id, suggestion_status, issuing_status, type, job_description
            - content, rejected_reason, delay_reason, suggested_id, issuer_id
            - suggested_at, issued_at, reminder_date, escalation_date
        
        14. user_details - Extended user information
            - id, user_id, profile_pic_path, date_of_birth, date_of_joining
            - aadhar_no, blood_group, gender, religion, pan_no, bank_account_no
            - ifsc_code, pf_account_no, uan, bank_name, nationality
        
        15. countries, states, cities - Geographic information
            - Standard location data with coordinates
        
        16. roles - User roles
            - id, name, display_name, description
        
        17. modules, tasks - Project structure
            - Project modules and associated tasks
        
        18. task_efforts - Task effort tracking
            - id, efforts, learning, assumption, task_id, module_id, team_id
        """
    
    def get_session(self):
        """Get database session"""
        return self.SessionLocal()
    
    def execute_query(self, query: str, params: Optional[Dict] = None) -> List[Dict[str, Any]]:
        """
        Execute a SQL query generated by LLM and return results
        
        Args:
            query: SQL query string generated by LLM
            params: Query parameters (if any)
            
        Returns:
            List of dictionaries containing query results
        """
        try:
            with self.get_session() as session:
                result = session.execute(text(query), params or {})
                rows = result.fetchall()
                
                # Convert to list of dictionaries
                columns = result.keys()
                return [dict(zip(columns, row)) for row in rows]
                
        except Exception as e:
            logger.error(f"Database query error: {str(e)}")
            logger.error(f"Failed query: {query}")
            raise e
    
    def get_schema_info(self) -> str:
        """Get database schema information for LLM context"""
        return self.schema_info


# Global database service instance
db_service = DatabaseService()
